### ISSUE TITLE
[WEB] Error on collapse and expand of the left pane

### ISSUE THREAD

**Issue by javac9** [joreilly/ClimateTraceKMP#107]
Steps to reproduce:

- start in web browser
- select a country in the left pane
- collapse the left pane
- expand the left pane

![image](https://github.com/user-attachments/assets/ed2dd86b-fb3d-498e-94d0-bf6d248413a5)

**Comment by joreilly** [comment]
So, looks like this was issue that started happening in CMP 1.7.x and seems to be related to combination of `animateDpAsState` for column width and `SearchBar`.  I've disabled animation for now.....will try and look in to it again another time.
