### ISSUE TITLE
3.0.0-wasm1 failing

### ISSUE THREAD

**Issue by ismai117** [joreilly/ClimateTraceKMP#5]
> Task :composeApp:compileKotlinIosX64 FAILED
warning: skipping /Users/ismail/.gradle/caches/modules-2/files-2.1/io.ktor/ktor-utils-iosx64/3.0.0-wasm1/3b5ee45cbb38eefb3c7cc5782c1c18f0448467fb/ktor-utils-cinterop-threadUtils.klib. The library versions don't match. Expected 'unspecified', found '3.0.0-wasm1'
error: Could not find "io.ktor:ktor-utils-cinterop-threadUtils" in [/Users/ismail/Downloads/Noor, /Users/ismail/.konan/klib, /Users/ismail/.konan/kotlin-native-prebuilt-macos-x86_64-1.9.21/klib/common, /Users/ismail/.konan/kotlin-native-prebuilt-macos-x86_64-1.9.21/klib/platform/ios_x64]
error: Compilation finished with errors

FAILURE: Build failed with an exception.

**Comment by joreilly** [comment]
Yeah, this is expected and I made this repo public at this point to act as reproducer of this issue https://kotlinlang.slack.com/archives/CDFP59223/p1701968310319679

**Comment by joreilly** [comment]
This is resolved now
